apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::515966500898:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-HiEmirvCuqIG
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - fresher
      userarn: arn:aws:iam::515966500898:user/arun
      username: arun
    
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-17T05:47:40Z"
  name: aws-auth
  namespace: kube-system
  uid: 6ea2e4d1-d739-451a-85f5-68a12ea71205




