apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::515966500898:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-HiEmirvCuqIG
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - fresher
      userarn: arn:aws:iam::515966500898:user/arun
      username: arun
    
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-17T05:47:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1358"
  uid: 58340a3d-73de-4830-ad7b-ad2b057c43ba

